name       : kpeople
version    : 5.59.0
release    : 25
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.59/kpeople-5.59.0.tar.xz : 8c1f440e3b27a3e6294ba8439a9c15f039af66f18db64d285da247b9d577ee41
license    : LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Provides access to all contacts and aggregates them by person
description: |
    KPeople offers unified access to our contacts from different sources, grouping them by person while still exposing all the data. Furthermore, KPeople will also provide facilities to integrate the data provided in user interfaces by providing QML and Qt Widgets components.
builddeps  :
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - ki18n-devel
    - kitemviews-devel
    - kservice-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
