name       : kpeople
version    : 5.44.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.44/kpeople-5.44.0.tar.xz : f10c056f23feb48907a764c1af9dff17771254089920abf4ba51602e9800e63e
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Provides access to all contacts and aggregates them by person
description: |
    KPeople offers unified access to our contacts from different sources, grouping them by person while still exposing all the data. Furthermore, KPeople will also provide facilities to integrate the data provided in user interfaces by providing QML and Qt Widgets components.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kservice-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
