name       : kpeople
version    : 5.35.0
release    : 2
source     :
    - https://download.kde.org/stable/frameworks/5.35/kpeople-5.35.0.tar.xz : c56ab4ad515bc67ad24e4d50e3bcd2acff0dae89ab36816c4c94307be3bf6c11
license    : LGPL-2.1
component  : programming
summary    : Provides access to all contacts and aggregates them by person
description: |
    KPeople offers unified access to our contacts from different sources, grouping them by person while still exposing all the data. Furthermore, KPeople will also provide facilities to integrate the data provided in user interfaces by providing QML and Qt Widgets components.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kservice-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
