name       : kpeople
version    : 5.40.0
release    : 6
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.40/kpeople-5.40.0.tar.xz : 79d550a16d6f68f0ceafbce1c34e39eb95256b95c8940e9cfff3317ec704daf9
license    : LGPL-2.1
component  : programming
summary    : Provides access to all contacts and aggregates them by person
description: |
    KPeople offers unified access to our contacts from different sources, grouping them by person while still exposing all the data. Furthermore, KPeople will also provide facilities to integrate the data provided in user interfaces by providing QML and Qt Widgets components.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kservice-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake -DBUILD_QCH=ON .
build      : |
    %make
install    : |
    %make_install
