name       : kpeople
version    : 5.78.0
release    : 44
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.78/kpeople-5.78.0.tar.xz : b180d9623f9ed0c83deb49a299bad6f7b88b50a2f83ea745d0c970e830088c31
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : Provides access to all contacts and aggregates them by person
description: |
    KPeople offers unified access to our contacts from different sources, grouping them by person while still exposing all the data. Furthermore, KPeople will also provide facilities to integrate the data provided in user interfaces by providing QML and Qt Widgets components.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
