name       : kpeople
version    : 5.99.0
release    : 61
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.99/kpeople-5.99.0.tar.xz : 7f05f4059d85371fafb9bbd1023b5995b6f8986c3fc4745a65f60513f71b663d
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : Provides access to all contacts and aggregates them by person
description: |
    KPeople offers unified access to our contacts from different sources, grouping them by person while still exposing all the data. Furthermore, KPeople will also provide facilities to integrate the data provided in user interfaces by providing QML and Qt Widgets components.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
