name       : kpeople
version    : 5.96.0
release    : 60
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.96/kpeople-5.96.0.tar.xz : ab84002eb7033f4cbc53eeca900844a139ae8fe20c4083592f7526d5e1036c60
homepage   : https://community.kde.org/Frameworks
license    : LGPL-2.1-or-later
component  : programming.tools
summary    : Provides access to all contacts and aggregates them by person
description: |
    KPeople offers unified access to our contacts from different sources, grouping them by person while still exposing all the data. Furthermore, KPeople will also provide facilities to integrate the data provided in user interfaces by providing QML and Qt Widgets components.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Quick)
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kwidgetsaddons-devel
setup      : |
    %cmake_ninja -DBUILD_QCH=ON \
                -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
