name       : kpeople
version    : 5.47.0
release    : 13
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.47/kpeople-5.47.0.tar.xz : 0bb7fad53b13bd1cb40d9339a0782b4902517b751f0f8271c1adc2ce6571a18f
license    : LGPL-2.1
component  : programming
optimize   : lto
summary    : Provides access to all contacts and aggregates them by person
description: |
    KPeople offers unified access to our contacts from different sources, grouping them by person while still exposing all the data. Furthermore, KPeople will also provide facilities to integrate the data provided in user interfaces by providing QML and Qt Widgets components.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5UiTools)
    - extra-cmake-modules
    - kcoreaddons-devel
    - ki18n-devel
    - kitemviews-devel
    - kservice-devel
    - kwidgetsaddons-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja -DBUILD_QCH=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
